### ISSUE TITLE
two xml routes

### ISSUE THREAD

**Issue by jaeho3690** [MIC-DKFZ/LIDC-IDRI-processing#6]
<img width="748" alt="스크린샷 2019-07-28 오후 3 07 23" src="https://user-images.githubusercontent.com/38973453/62002972-b477f480-b149-11e9-8d84-6f96c9a48ecc.png">

Hello, sir I was wondering if there is any particular reason why you have made two xml routes in your code. It is just a typo? Thanks

**Comment by jaeho3690** [comment]
I am also curious if there is anyone who have succeeded in Linux server, as we seem to be having the same problem as 
Duplicate of #1  is facing.

**Comment by MiGoetz** [comment]
First, sorry that it took me a while to come back to you. 

The answer why there are two path_to_xmls is that I tried to versions and wanted to obtain both paths in the code. Especially since this code was never ment to be released, and is just public because of multiple requests. 

So in some sense: Yes, it's a kind of typo

**Comment by MiGoetz** [comment]
With regards to your Linux question: If you read the thread you're reference you'll find some solutions. It seems that there had been sucessfull approaches. However, I haven't tried it for myslef for some time, so I'm not sure.
